### ISSUE TITLE
1.7.1 deleted quotes in JS dictionaries

### ISSUE THREAD

**Issue by key-notes** [alexanderweiss/nova-prettier#36]
Quotes are often yet arbitrarily deleted in dictionaries. Most keys that are strings are properly in quotes, yet for other keys the quotes are removed. There seems to be no discernible trigger or pattern. Unfortunately this bug renders 1.7.1 unusable for JS.

**Comment by alexanderweiss** [comment]
Do you have an example file / part of a file? Were you using a different version previously? And do you have Prettier installed in your project? If so, you can double-check in the extension console (enable Extension development in Nova preferences, then a new item appear in the menu bar) if it's actually using that version of Prettier. Prettier defaults to using quotes only where they're needed (for example when the name contains `-`) and removing them otherwise: https://prettier.io/docs/en/options.html#quote-props

**Comment by key-notes** [comment]
Hi Alexander,

Yes, I have an example. Is there a way I can send you code privately?


Many thanks,

Albert

**Comment by alexanderweiss** [comment]
You can send me an email. My address is on my website.

**Comment by alexanderweiss** [comment]
I think this is also just he Prettier defaults, right? If not, you're welcome to reopen it.
