### ISSUE TITLE
Doesn't work for Remote opened files. 

### ISSUE THREAD

**Issue by highree** [alexanderweiss/nova-prettier#37]
It seems that the config file works only for locally opened files. If I open a remote file, the config file is being ignored. 
i am using Catalina + Nova + Noiva prettier 1.7.1

**Comment by alexanderweiss** [comment]
Yes, I'm aware of that (see #31). Prettier obviously doesn't automatically resolve that file because it runs on your computer, not the remote. And actually finding the `.prettierrc` on the remote might be complex.  I was planning on adding an option to set the Prettier configuration in the Nova project settings. Do you think that's a reasonable solution?

**Comment by highree** [comment]
oh hell yes, that would be great. Sorry for creating another topic, i haven't seen that one because the title isn't really saying something similar. For me the formatter is working for all files, but just in standard config. Ideally would be great if it works project based. But if u just create a textfield where we can put our config in, that'll be great!

**Comment by alexanderweiss** [comment]
No problem. It's not very obvious indeed. Would you prefer proper separate input fields for each option or just a single textfield for the .prettierrc contents?

**Comment by highree** [comment]
I think I would prefer one textfield, which gives me the possibility to just copy and paste my config. Probably most easy way for everyone.

**Comment by alexanderweiss** [comment]
The latest release (v1.8.0) now allows you to set the default Prettier configuration options in the extension preferences. You can also set them at the project level. A text field turned out to have some issues. So it's become separate options after all.
