### ISSUE TITLE
Format on save unfolds all the code

### ISSUE THREAD

**Issue by DhvanilPatel** [alexanderweiss/nova-prettier#69]
Hi, thank you for creating this. I've been using nova-prettier very heavily – and it has made my life much simpler.

There's one small issue I'd like to bring to your notice. Whenever I save my unformatted code, the extension unfolds the code too.

Steps to reproduce:
1. Open a JS document
2. Fold some functions, JSON objects, arrays (anything really & at any level)
3. Change the formatting of other parts of the code (add some spaces, indent some lines of code, etc)
4. Save the document
5. **The document will automatically unfold**

Maybe related to this: https://github.com/prettier/prettier-vscode/issues/408?

**Comment by alexanderweiss** [comment]
Hey! Great to hear!

This is because Nova the extension replaces the text in the file and Nova doesn't take into account that some things aren't changed and just unfolds everything.

Previously the extension would specifically tell Nova only to update changed bits of the content as Nova otherwise didn't even maintain the cursor position(s). That meant this was less of a problem because it would only unfold things that the formatting actually changed. However the diffing required for that can be really slow. Especially when there's many changes. So it was really slow and annoying sometimes. When Panic fixed the cursors positions not being maintained I removed that special replacing logic (see https://github.com/alexanderweiss/nova-prettier/issues/66).

I'd suggest reporting this problem to Panic. I'll also contact them soon, because the cursor positions are still off as well it seems.

**Comment by DhvanilPatel** [comment]
Thank you. I just send an email + tweet to Panic! Will update here if they revert back. :)

**Comment by logancollins** [comment]
Hello all! Our support team linked me to this thread to give some more in-depth info where I can (based on this thread and your tweets to Panic).

Specifically related to cursor positions after changes to a document from an extension:

Nova doesn't currently attempt to maintain the exact cursor position(s) that exist within a range that is then modified by an extension, but (as of Nova 4, I think?) it also no longer moves the cursor to the end of that range when performing the replace operation. For example: if you place the cursor at column 4, and then an extension replaces text before that point, it will remain at position 4 unless the extension tells us otherwise.

We can consider adding some actual diffing to maintain the cursor position (and folding ranges) relative to code around it. It's just not something Nova is equipped to handle right away, sadly.

**Comment by alexanderweiss** [comment]
Thanks for the extra info @logancollins! I'll bring back the diffing for now then. Would be awesome if Nova did it itself. As I mentioned above it can be pretty slow, especially if you have multiple extensions all doing their own diffing.

**Comment by steveblue** [comment]
Thanks for all the great work on this extension. I can reproduce the issue in Nova 6.1 / Prettier 2.2.1.

**Comment by DhvanilPatel** [comment]
Thank you so much! It works perfectly now ✨. I'm closing this issue 💫
