### ISSUE TITLE
The extension "Prettier" has stopped responding.

### ISSUE THREAD

**Issue by edaptivemedia** [alexanderweiss/nova-prettier#76]
I have the prettier extension installed in Nova, and am able to access the menu. Currently "Format Selection" does nothing, and "Format" appears to do nothing, but then about 30 seconds later I get a Nova prompt that says "The extension "Prettier" has stopped responding." I have the option to Wait or Restart Extensions. Regardless of what I select, a few seconds later, the whole document does appear to get reformatted.

<img width="877" alt="Screen Shot 2021-06-16 at 11 09 53 AM" src="https://user-images.githubusercontent.com/86009458/122245063-641bf400-ce93-11eb-9ff6-ff8dafff71aa.png">

**Comment by dtomasch** [comment]
I get the same issue here.

**Comment by alexanderweiss** [comment]
Is this by any chance a long or complex document or one with many changes when formatting? If so, this is because in those cases it's slow to apply the changes made by Prettier. The extension has to find all the changed parts of the document and apply those changes separately, because otherwise things like code folding & cursor positions break. It's a known issue and hard to improve without Panic doing this in the app itself. In general subsequent formatting / saves should be way faster because there's fewer changes.

**Comment by yabdab** [comment]
I had this issue all the time so now I only format manually instead of on save.

**Comment by edaptivemedia** [comment]
> Is this by any chance a long or complex document or one with many changes when formatting?

@alexanderweiss I'm not sure what you would consider a complex document, but the one I was specifically working on when I encountered the issue was 1200 lines, with a moderate amount of formatting needed.

**Comment by alexanderweiss** [comment]
@edaptivemedia, so does it improve after the first time it's formatted?

**Comment by alexanderweiss** [comment]
Closing this as it's been so long, but feel free to reopen if it's still relevant
