### ISSUE TITLE
Cannot find module 'prettier-plugin-svelte'

### ISSUE THREAD

**Issue by jakobbouchard** [alexanderweiss/nova-prettier#94]
Hello, I am trying to use this extension in a SvelteKit project and it doesn't seem to be working when using the Svelte plugin. In fact, it seems that plugins don't work at all. Removing them from the config works fine however.

**Comment by jakobbouchard** [comment]
Using this syntax

```js
plugins: ['./node_modules/prettier-plugin-svelte'],
```

instead of

```js
plugins: ['prettier-plugin-svelte'],
```

seems to work, but it's not really the intended way to use it, plus it's the only integration/plugin that has issues with it in my experience. I also tried setting the `pluginSearchDirs` option, which didn't help either.

**Comment by jakobbouchard** [comment]
Also, the PR #92 seems to fix this issue, as I tested it successfully :)

**Comment by battis** [comment]
+1 to both the issue as described by @jakobbouchard and also to PR #92 fixing the problem.

_However…_ PR #92 works if I use npm. If I use pnpm. I need use the `--shamefully-hoist` flag for it to work successfully (which isn't that shocking -- pnpm is awesome, but lots of tools don't play super-nice with its package resolution).

**Comment by alexanderweiss** [comment]
I can't seem to reproduce this I'm afraid. Any chance you can provide more specific steps / details about your structure and setup?

**Comment by battis** [comment]
I'm running into a version of this with my setup.

- I have a shared Prettier config in [@battis/prettier-config](https://github.com/battis/prettier-config)
- That configuration includes two plugins as peer dependencies: [pretter-plugin-sql](https://www.npmjs.com/package/prettier-plugin-sql) and [@prettier/plugin-xml](https://www.npmjs.com/package/@prettier/plugin-xml).
- I use `pnpm` rather than `npm` because… well, because disk space is finite, and so is my time and patience. But it does introduce headaches into my life.
- In an average project (I'm working on [this one](https://github.com/groton-school/course-planning-tool) today, I include`@battis/prettier-config` as a devDependency, and update my `.npmrc` file to hoist anything with "prettier" in its name (so that `prettier` and its plugins are all where they would be if `npm` was managing dependencies).
- I configure `prettier` using the `prettier` field in `package.json`
- I install no global dependencies through either `pnpm` or `npm`, to ensure that my project config files accurately capture dependencies.
- I believe my extension settings are still the defaults (I've tinkered some, but since nothing fixed it, I went back to the original settings).

What I'm finding (at the moment), is that when I save a TypeScript file, it looks like `prettier` is run, but I get an error:

> *Error while formatting*
>
> "Cannot find module 'prettier-plugin-sql'
> Require stack:
> - /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js
> - /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js"
> occurred wile formatting /Users/sbattis/Documents/GitHub/course-planning-tool/src/AddOn.ts. See the extension console for more.

And the extension console says:

```
Prettier[10:04:22.253000] [object Object] Error: Cannot find module 'prettier-plugin-sql'
Require stack:
- /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js
- /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at resolve (node:internal/modules/helpers:125:19)
    at /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:60854:21
    at Array.map (<anonymous>)
    at Object.load (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:60846:61)
    at Object.load [as loadPlugins] (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:18147:23)
    at /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:60920:28
    at Object.format (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:60942:12)
    at PrettierService.format (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js:51:35)
    at async JsonRpcService.processRequest (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/json-rpc.js:135:19)
```
Invoking prettier from the command line:

```bash
npx prettier --write src/AddOn.ts
```
…results in no errors.

Of course, as expected, the Nova extension does not run on SQL and XML files. (Although they can be formatted fine from the command line. Well, SQL can… XML is being a tool right this second. Probably because of `pnpm` and hoisting.)

**Comment by battis** [comment]
I'm low bandwidth right now, but am generally happy to help if I can.

**Comment by alexanderweiss** [comment]
Yeah, that works too. 😁

I've created a pre-release for the latest changes: https://github.com/alexanderweiss/nova-prettier/releases/download/v2.5.0/prettier.novaextension.zip. It changes the way the extension finds your Prettier installation to not use `npm`, but just traverse the filesystem instead. It doesn't currently support global installations. But it didn't before either.

I've only tested it with `npm` and `yarn`, not `pnpm` yet, because brew was being annoying. If you have some time it'd be great if you could try it and see if it works / check the logs to see which Prettier installation the extension tries to use @battis. Thanks!

**Comment by battis** [comment]
Same error, unfortunately.

```
Prettier[11:04:39.103000] [object Object] Error: Cannot find module 'prettier-plugin-sql'
Require stack:
- /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js
- /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at resolve (node:internal/modules/helpers:125:19)
    at /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:38119:25
    at Array.map (<anonymous>)
    at Object.load (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:38114:65)
    at Object.load [as loadPlugins] (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:16147:23)
    at /Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:38181:24
    at Object.format (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:38197:12)
    at PrettierService.format (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js:51:35)
    at async JsonRpcService.processRequest (/Users/sbattis/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/json-rpc.js:135:19)
```

**Comment by alexanderweiss** [comment]
@battis I'll dig a bit deeper then. What prettier installation does the updated version use for you though? Is it still the embedded prettier?

**Comment by alexanderweiss** [comment]
@battis & @benwittorf I've figured out an issue with plugin resolution and [uploaded a new pre-release](https://github.com/alexanderweiss/nova-prettier/releases/download/v2.5.0/prettier.novaextension.zip). That should make it work with `npm` out of the box (does for me). For `pnpm` I still need to add the following to `.prettierrc`:

```json
"plugins": ["prettier-plugin-svelte"],
"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
```

Though I need to add that to make it work with the prettier CLI as well. so I'm thinking that's just something between prettier and `pnpm`.

For you I think we'll first need to figure out why it's trying to use the embedded prettier and not your project's prettier. The pre-release version should definitely use your project installation. Unless it's not just in `node_modules`. Could you share the following:
- Your workspace path (so the root path of your Nova project)
- The path of the prettier module you want / expect Prettier to use (the one installed in your project)
- The package manager you use. `pnpm` and `npm` right?

**Comment by battis** [comment]
Looks good -- definitely no error messages _and_ prettier formatting in "normal" files (`.js`, `.json`, `.html`, `.ts`).

- workspace path: `$HOME/Documents/GitHub/course-planning-tool` (or whatever else -- they're all in that GitHub directory)
- prettier module path: `$HOME/Documents/GitHub/course-planning-tool/node_modules/prettier`
- package manager: `pnpm`

Currently tinkering with prettier/pnpm config to get it to work on the CLI for wackier situations.

**Comment by alexanderweiss** [comment]
Good to hear @benwittorf! Thanks for trying out! It's released on the extension library now.

@battis, so is it different from just using Prettier on the command line new? In my testing it seems to require the same config / workarounds on the command line as in the extension now.

**Comment by battis** [comment]
@alexanderweiss You are correct -- command line and extension seem to be in agreement!
